import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import theme from './theme'
import './globals.scss'
import Header from './components/header/header'
import { Container } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <script src='https://unpkg.com/pose-viewer@latest/dist/pose-viewer/pose-viewer.esm.js' type='module' async />
      </head>
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider>
            <Header />
            <Container maxWidth='lg' sx={{ mt: 1.5 }}>
              {children}
            </Container>
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
