import { Container, CssBaseline } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

import theme from './theme'
import './globals.scss'
import AuthProviders from './(user)/auth/auth-providers'
import Header from './components/header/header'
import Footer from './components/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DnD Translate',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <title>DnD Translate</title>
        <script src='https://unpkg.com/pose-viewer@latest/dist/pose-viewer/pose-viewer.esm.js' type='module' async />
      </head>
      <body className={inter.className}>
        <CssBaseline />
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider>
            <AuthProviders>
              <Header />
              {/* <Container maxWidth='lg' sx={{ mt: '71px' }}> */}
              <ToastContainer
                position='bottom-left'
                autoClose={4000}
                hideProgressBar
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                pauseOnHover
                theme='light'
                style={{ marginBottom: 30 }}
              />
              {children}
              {/* </Container> */}
              <Footer />
            </AuthProviders>
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
