import { Container } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProviders from './auth/auth-providers'
import Footer from './components/footer/footer'
import Header from './components/header/header'
import './globals.scss'
import theme from './theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <title>DnD Translate</title>
        <script src='https://unpkg.com/pose-viewer@latest/dist/pose-viewer/pose-viewer.esm.js' type='module' async />
      </head>
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <AppRouterCacheProvider>
            <AuthProviders>
              <Header />
              <Container maxWidth='lg' sx={{ mt: 1.5, mb: 6 }}>
                {children}
              </Container>
              <Footer />
            </AuthProviders>
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
